name: Code Style
on:
  push:
    paths:
      - '**.go'
#      - '**.py'

jobs:
  lint-go:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golanci/golangci-lint-action@v2
        with:
          working-directory: ServerSrc
          skip-go-installation: true
          args: -E bodyclose -E dupl -E goconst -E godox -E gosec -E sqlclosecheck -E wastedassign
#  lint-python:
