name: Test
on:
  push:
    - 'ServerSrc/**.go'
    - 'ServerTest/**'
permissions:
  contents: read

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ServerSrc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: |
          go build -v

#  functional:
#    name: Functional tests
#    runs-on: ubuntu-latest
#    needs: build
#    defaults:
#      run:
#        shell: bash
#        working-directory: ServerTest/Functional
#    steps:
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.9'
#      - run: |
#          pip3 install requests
#          ../../ServerSrc/Cryptik -i 8085 &
#          sleep 1 # allow server to start up
#          python3 harness.py
#
#  performance:
#    name: Performance/Stress tests
#    runs-on: ubuntu-latest
#    needs: build
#    defaults:
#      run:
#        shell: bash
#        working-directory: ServerTest/Performance
#    steps:
#      - run: |
#          ../../ServerSrc/Cryptik -i 8086 &
#          ./Sequential
#          ./Concurrent
