name: Test
on:
  push:
    paths:
      - 'ServerSrc/**.go'
      - 'ServerTest/**'
permissions:
  contents: read

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ServerSrc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: go build -v
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ServerSrc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: go test -v

#  functional:
#    name: Functional tests
#    runs-on: ubuntu-latest
#    needs: build
#    defaults:
#      run:
#        shell: bash
#        working-directory: ServerTest/Functional
#    steps:
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.9'
#      - run: |
#          pip3 install requests
#          ../../ServerSrc/Cryptik -i 8085 &
#          sleep 1 # allow server to start up
#          python3 harness.py
